version: "3"

services:
  mysql:
    container_name: todos-db
    image: mysql:latest
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todos
